#!/bin/bash
# This script reads an file, which contains a call to slicing in each line
# and stores the resulting log files in an extra folder

while read -r line; do
	../scritps/clear
	cmd=${line#*\ }
	name=${line%% *}
	mkdir -p "logs/$name"
	logDir=$(mktemp -dp logs/ "$name/XXX")
	eval $cmd > "$logDir/out"
	cp log $logDir
	ln -sf "$(pwd)/$logDir/log" "$(pwd)/logs/$name/log"
	cp program.llvm $logDir
	cp slice.llvm $logDir
done < $1

shutdown