#!/bin/bash
# This script reads an file, which contains a call to slicing in each line
# and stores the resulting log files in an extra folder

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

while read -r line; do
	#skip empty lines
	[ -z "$line" ] && continue
	$DIR/clear
	cmd=${line#*\ }
	name=${line%% *}
	mkdir -p "logs/$name"
	logDir=$(mktemp -dp logs/ "$name/XXX")
	echo "$cmd"
	eval $cmd > "$logDir/out"
	if [ $? -ne 0 ]; then
		echo "Error during execution!"
		exit 2
	fi
	cp log $logDir
	ln -sf "$(pwd)/$logDir/log" "$(pwd)/logs/$name/log"
	cp program.llvm $logDir
	cp slice.llvm $logDir
done < $1

#shutdown