#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ $# -eq 0 ]]; then
	$DIR/prepare program.llvm
	$DIR/prepare slice.llvm
	meld program.llvm slice.llvm
else
	name=${1%.}
	name=${name%.orig}

	orig=$name.orig
	slice=$name.slice

	if [ ! -f $orig ]; then
		echo "Could not find original program: $orig"
		exit 2
	fi
	if [ ! -f $slice ]; then
		echo "Could not find sliced program: $slice"
		exit 2
	fi

	DIR/prepare $orig
	DIR/prepare $slice
	meld $orig $slice
fi